# Site settings
baseurl = "/"
languageCode = "fr"
title = "Hugues Blog"
theme = "hugo-theme-cactus-plus-master"
googleAnalytics = "UA-116046902-1"

# ignore files (or folder) during build (based on path pattern matching)
ignoreFiles = [ "raw-material" ]

[params]
	author = "Hugues"
	description = "Blog"
	bio = "Sur le chemin du retour"


	twitter = "chug"
	# facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "huguesblog"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	# twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "Accueil"
	about = "A propos"
	archive = "Historique"
	subscribe = "RSS"

	olderPosts = "précédent"
	newerPosts = "suivant"
	copyright = " "

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Non trouvée"
	subtitle404 = "Le contenu que vous recherchez ne semble pas exister."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	twitter-square = "https://www.twitter.com/chug"
	# github-square = "https://www.github.com/"
